name: Publish to pub.dev

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Increment Version
        id: bump_version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ':' -f 2 | tr -d '[:space:]')
          echo "Current version: $VERSION"
          
          IFS='.' read -ra ADDR <<< "$VERSION"
          MAJOR=${ADDR[0]}
          MINOR=${ADDR[1]}
          PATCH=${ADDR[2]}
          
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "New version: $NEW_VERSION"
          
          sed -i "s/^version: .*/version: $NEW_VERSION/" pubspec.yaml
          
          DATE=$(date +%Y-%m-%d)
          TEMP_CHANGELOG=$(mktemp)
          echo -e "## $NEW_VERSION\n\n- Automatic release on push to main ($DATE)\n\n$(cat CHANGELOG.md)" > "$TEMP_CHANGELOG"
          mv "$TEMP_CHANGELOG" CHANGELOG.md
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pubspec.yaml CHANGELOG.md
          git commit -m "chore: bump version to ${{ steps.bump_version.outputs.new_version }} [skip ci]"
          git push

      - name: Verify publishing eligibility
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: flutter pub publish --force
